name: Rust CI Config
description: Merge Rust CI Config
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  runner:
    description: 'Runner to use for CI'
    required: false
outputs:
  config:
    description: 'Configuration JSON output'
    value: ${{ steps.config.outputs.config }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
    - name: config
      id: config
      uses: carteramesh/ci@ts-baby
